
# If you receive an error when you load this plugin
# Make sure that:
# There are no taps
# Text with symbols is enclosed in single or double quotation marks

# This sets you server name:
ServerName: 'YourServerName'

#Staff here
staff:
    - Example1
    - Example2
