
# If you receive an error when you load this plugin
# Make sure that:
# There are no taps
# Text with symbols is enclosed in single or double quotation marks

# This sets you server name:
ServerName: 'YourServerName'

#Staff here
staff:
    - The_Han_Solo(Owner)
    - Alescia(Co-Owner)
    - LightningValley(Head-Admin)
    - 20mathias20(Admin)
    - Redy4580(Dev)
    - Fido2603(Moderator)