name: Staff-1.7.10
main: dk.fido2603.staff.Staff
version: 0.0.1
description: A quick staff check thingy.
softdepend: [GroupManager]
commands:
  staff:
    usage: /<command>
    description: The command for the Staff plugin.
permissions:
  staff.*:
    description: Gives permission to all of the Staff plugins commands.
    default: false
    children:
      staff.add: true
      staff.reload: true
      staff.help: true
      staff.info: true
      staff.staff: true
  staff.add:
    description: Permission to add staff to list.
    default: false
  staff.reload:
    description: Permission to reload the plugin.
    default: false
  staff.help:
    description: Permission to use the help command.
    default: true
  staff.info:
    description: Permission to use the info command.
    default: true
  staff.staff:
    description: Permission to view the staff.
    default: true

